chore(protolint): add buf to pre-commit checks

diff --git a/.cargo-husky/hooks/pre-commit b/.cargo-husky/hooks/pre-commit
--- a/.cargo-husky/hooks/pre-commit
+++ b/.cargo-husky/hooks/pre-commit
@@ -26,6 +26,12 @@ cargo clippy --all --all-features -- -D warnings || {
   exit 1
 }
 
+echo 'Running buf'
+buf lint proto/. || {
+  echo >&2 'Buf failed. This most likely means you have linting errors in .proto files'
+  exit 1
+}
+
 declare -a file_array=()
 for file in $files_to_git_add; do
   file_array+=("${file}")
